### ISSUE TITLE
How to get gainfile?

### ISSUE THREAD

**Issue by mgcyung** [caseyjlaw/FRB121102#2]
I have downloaded a sdm data set  from https://archive.nrao.edu/archive.  How to get gainfiles for sdm files in it?

**Comment by caseyjlaw** [comment]
You can find that along with the data on dataverse.

**Comment by mgcyung** [comment]
The sdm data I have downloaded is from "http://archive.nrao.edu" but
not on the dataverse. How to get the gainfile of it?

**Comment by caseyjlaw** [comment]
Ah, I see. This repo is designed for reproducing the results in a published paper. The data for that paper and the gainfiles are at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TLDKXG.

**Comment by mgcyung** [comment]
Yes, I want to try the pipeline on other data set. But I haven't found
gainfiles for the new sdm file. I wonder how these gainfiles are
generated? Maybe I can do it for the new sdm file.

On Thu, 17 Oct 2019 01:24:49 +0800,
Casey Law wrote:

**Comment by caseyjlaw** [comment]
Ah, I understand.
The gainfiles are not publicly available at the moment. We shared them for this data for FRB 121102 and we have plans to include gain calibration in new data. However, currently it is not possible to get gain solutions for any data on the archive.

**Comment by mgcyung** [comment]
Ok, I see.

Can I produce the gainfile with the package telcal? I saw
some code about the gainfile in the rtpipe package
``` python
        # calibrate data
        if os.path.exists(d['gainfile']):
            try:
                radec = (); spwind = []; calname = ''  # set defaults
                if '.GN' in d['gainfile']: # if telcal file
                    if d.has_key('calname'):
                        calname = d['calname']

                    sols = pc.telcal_sol(d['gainfile'])   # parse gainfile
                else:   # if CASA table
                    if d.has_key('calradec'):
                        radec = d['calradec']  # optionally defined cal location

                    spwind = d['spw']
                    sols = pc.casa_sol(d['gainfile'], flagants=d['flagantsol'])   # parse gainfile
                    sols.parsebp(d['bpfile'])   # parse bpfile

                # if gainfile parsed ok, choose best solution for data
                sols.set_selection(d['segmenttimes'][segment].mean(), d['freq']*1e9, rtlib.calc_blarr(d), calname=calname, pols=d['pols'], radec=radec, spwind=spwind)
                sols.apply(data_read)
            except:
                logger.warning('Could not parse or apply gainfile %s.' % d['gainfile'])
                raise
        else:
            logger.warn('Calibration file not found. Proceeding with no calibration applied.')
```

**Comment by caseyjlaw** [comment]
Thanks for your enthusiasm!
I have not tested that for a while, so it is not currently supported. I think it would be best to wait until we start to archive data with calibration solutions included in the file. The NRAO will archive those hopefully in the next few months. Then you can just download one file and have everything ready to go for the rfpipe package.

**Comment by mgcyung** [comment]
Ok, maye I should try some other ways. Thanks for your work and
advice.
